// DUMMY_DATA: admin seed — remove when backend is ready

import { DUMMY_IDS } from "@/dummy/_ids.dummy";
import { BLOG_POSTS } from "@/data/blogs";
import { FAQS } from "@/data/faqs";
import { PRODUCT_REVIEWS } from "@/data/reviews";
import type {
  AdminAffiliateApplication,
  AdminAffiliateProgram,
  AdminBlogPost,
  AdminCategory,
  AdminCustomer,
  AdminCustomizeOrder,
  AdminFaq,
  AdminHeroBanner,
  AdminOffer,
  AdminOrder,
  AdminProduct,
  AdminReview,
  AdminSettings,
  AdminWholesaleInquiry,
  AdminWholesaleSeller,
} from "@/types/admin";

const now = "2026-08-01T10:00:00.000Z";

export const adminCategoriesSeed: AdminCategory[] = [
  {
    _id: DUMMY_IDS.categoryLadies,
    name: "Ladies",
    slug: "ladies",
    image: "/Image/ImagesPage/ladies.webp",
    parentId: null,
    isActive: true,
    sortOrder: 1,
    createdAt: now,
  },
  {
    _id: DUMMY_IDS.categoryGents,
    name: "Gents",
    slug: "gents",
    image: "/Image/ImagesPage/gents.webp",
    parentId: null,
    isActive: true,
    sortOrder: 2,
    createdAt: now,
  },
  {
    _id: DUMMY_IDS.subLadiesLace,
    name: "Lace Front",
    slug: "lace-front",
    parentId: DUMMY_IDS.categoryLadies,
    isActive: true,
    sortOrder: 1,
    createdAt: now,
  },
  {
    _id: DUMMY_IDS.subLadiesSilk,
    name: "Silk Top",
    slug: "silk-top",
    parentId: DUMMY_IDS.categoryLadies,
    isActive: true,
    sortOrder: 2,
    createdAt: now,
  },
  {
    _id: DUMMY_IDS.subGentsLace,
    name: "Gents Lace",
    slug: "gents-lace",
    parentId: DUMMY_IDS.categoryGents,
    isActive: true,
    sortOrder: 1,
    createdAt: now,
  },
  {
    _id: DUMMY_IDS.subGentsFull,
    name: "Full Cap",
    slug: "full-cap",
    parentId: DUMMY_IDS.categoryGents,
    isActive: true,
    sortOrder: 2,
    createdAt: now,
  },
];

export const adminProductsSeed: AdminProduct[] = [
  {
    _id: DUMMY_IDS.product1,
    name: "Lace Front Natural Black Wig",
    description: "Premium remy human hair lace front wig with natural hairline.",
    price: 280,
    discount: 10,
    images: ["/Image/Black/1jetblack.webp"],
    categoryId: DUMMY_IDS.categoryLadies,
    subCategoryId: DUMMY_IDS.subLadiesLace,
    stock: 12,
    isFeatured: true,
    available: true,
    addons: [{ name: "Cap Size", value: "Medium", price: 0 }],
    createdAt: now,
  },
  {
    _id: DUMMY_IDS.product2,
    name: "Full Cap Straight Wig",
    description: "Full cap straight style, easy to wear and maintain.",
    price: 220,
    discount: 0,
    images: ["/Image/Brown/2 DARKEST BROWN.webp"],
    categoryId: DUMMY_IDS.categoryGents,
    subCategoryId: DUMMY_IDS.subGentsFull,
    stock: 8,
    isFeatured: false,
    available: true,
    addons: [],
    createdAt: now,
  },
  {
    _id: DUMMY_IDS.product3,
    name: "Silk Top Bob Wig",
    description: "Natural silk top bob for everyday elegance.",
    price: 310,
    discount: 15,
    images: ["/Image/Blonde/613 PLATINUM BLONDE.webp"],
    categoryId: DUMMY_IDS.categoryLadies,
    subCategoryId: DUMMY_IDS.subLadiesSilk,
    stock: 3,
    isFeatured: true,
    available: true,
    addons: [],
    createdAt: now,
  },
  {
    _id: DUMMY_IDS.product4,
    name: "Mono Base Classic",
    description: "Durable mono base with soft remy hair.",
    price: 260,
    discount: 5,
    images: ["/Image/custom/wigs1.jpg"],
    categoryId: DUMMY_IDS.categoryLadies,
    stock: 15,
    isFeatured: false,
    available: true,
    addons: [],
    createdAt: now,
  },
  {
    _id: DUMMY_IDS.product5,
    name: "Gents Lace Unit",
    description: "Lightweight lace unit for men.",
    price: 190,
    discount: 0,
    images: ["/Image/Black/1B 0ff black.webp"],
    categoryId: DUMMY_IDS.categoryGents,
    subCategoryId: DUMMY_IDS.subGentsLace,
    stock: 0,
    isFeatured: false,
    available: false,
    addons: [],
    createdAt: now,
  },
];

export const adminHeroBannersSeed: AdminHeroBanner[] = [
  {
    _id: "hero_1",
    image: "/Image/ImagesPage/ladies.webp",
    isActive: true,
    sortOrder: 1,
    createdAt: now,
  },
  {
    _id: "hero_2",
    image: "/Image/ImagesPage/gents.webp",
    isActive: true,
    sortOrder: 2,
    createdAt: now,
  },
  {
    _id: "hero_3",
    image: "/Image/ImagesPage/why-choose-us.webp",
    isActive: false,
    sortOrder: 3,
    createdAt: now,
  },
];

export const adminOffersSeed: AdminOffer[] = [
  {
    _id: "offer_1",
    title: "Lace Front Spring Sale",
    productId: DUMMY_IDS.product1,
    discountPercent: 10,
    startsAt: "2026-07-01T00:00:00.000Z",
    endsAt: "2026-09-30T23:59:59.000Z",
    isActive: true,
    bannerImage: "/Image/Black/1jetblack.webp",
    createdAt: now,
  },
  {
    _id: "offer_2",
    title: "Silk Top Flash Deal",
    productId: DUMMY_IDS.product3,
    discountPercent: 15,
    startsAt: "2026-08-01T00:00:00.000Z",
    endsAt: "2026-08-31T23:59:59.000Z",
    isActive: true,
    createdAt: now,
  },
];

export const adminOrdersSeed: AdminOrder[] = [
  {
    _id: DUMMY_IDS.order1,
    customerName: "Sarah Ahmed",
    customerEmail: "sarah@example.com",
    status: "processing",
    paymentStatus: "paid",
    trackingStep: "processing",
    total: 300,
    subtotal: 280,
    deliveryCharge: 20,
    discount: 0,
    currency: "USD",
    orderItems: [
      {
        _id: "oi_1",
        name: "Lace Front Natural Black Wig",
        price: 280,
        quantity: 1,
        image: "/Image/Black/1jetblack.webp",
      },
    ],
    shippingAddress: {
      street: "12 Maple Street",
      city: "Dhaka",
      state: "Dhaka",
      country: "Bangladesh",
      postalCode: "1205",
    },
    createdAt: "2026-08-03T08:00:00.000Z",
  },
  {
    _id: DUMMY_IDS.order2,
    customerName: "John Miller",
    customerEmail: "john@example.com",
    status: "shipped",
    paymentStatus: "paid",
    trackingStep: "shipped",
    total: 440,
    subtotal: 440,
    deliveryCharge: 0,
    discount: 20,
    currency: "USD",
    orderItems: [
      {
        _id: "oi_2",
        name: "Full Cap Straight Wig",
        price: 220,
        quantity: 2,
        image: "/Image/Brown/2 DARKEST BROWN.webp",
      },
    ],
    shippingAddress: {
      street: "88 Oak Ave",
      city: "New York",
      state: "NY",
      country: "USA",
      postalCode: "10001",
    },
    createdAt: "2026-08-02T12:30:00.000Z",
  },
  {
    _id: DUMMY_IDS.order3,
    customerName: "Nadia Khan",
    customerEmail: "nadia@example.com",
    status: "payment_pending",
    paymentStatus: "pending",
    trackingStep: "payment_pending",
    total: 330,
    subtotal: 310,
    deliveryCharge: 20,
    discount: 0,
    currency: "USD",
    note: "Gift wrap requested",
    orderItems: [
      {
        _id: "oi_3",
        name: "Silk Top Bob Wig",
        price: 310,
        quantity: 1,
        image: "/Image/Blonde/613 PLATINUM BLONDE.webp",
      },
    ],
    createdAt: "2026-08-04T06:15:00.000Z",
  },
];

export const adminWholesaleSellersSeed: AdminWholesaleSeller[] = [
  {
    _id: "ws_1",
    name: "Beauty Hub BD",
    email: "orders@beautyhub.com",
    phone: "+8801711000001",
    company: "Beauty Hub Ltd",
    status: "approved",
    createdAt: now,
  },
  {
    _id: "ws_2",
    name: "Hair Pro Store",
    email: "contact@hairpro.com",
    phone: "+12025550123",
    company: "Hair Pro Inc",
    status: "pending",
    createdAt: "2026-08-03T09:00:00.000Z",
  },
];

export const adminWholesaleInquiriesSeed: AdminWholesaleInquiry[] = [
  {
    _id: "wi_1",
    name: "Lisa Chen",
    email: "lisa@salon.co",
    phone: "+14155550111",
    message: "Looking for bulk lace front units, MOQ 20.",
    status: "Pending",
    createdAt: "2026-08-03T11:00:00.000Z",
  },
  {
    _id: "wi_2",
    name: "Omar Faruk",
    email: "omar@retail.bd",
    message: "Interested in gents collection wholesale pricing.",
    status: "Contacted",
    createdAt: "2026-07-28T14:00:00.000Z",
  },
];

export const adminCustomizeOrdersSeed: AdminCustomizeOrder[] = [
  {
    _id: "co_1",
    name: "Emily Ross",
    email: "emily@example.com",
    phone: "+447700900123",
    baseMaterial: "Lace",
    hairMaterial: "Remy",
    hairDirection: "Left parting",
    notes: "Need 22 inch, density 180%, medium brown.",
    status: "new",
    createdAt: "2026-08-04T07:00:00.000Z",
  },
  {
    _id: "co_2",
    name: "Karim Hossain",
    email: "karim@example.com",
    baseMaterial: "Mono",
    hairMaterial: "Virgin",
    hairDirection: "Free style",
    notes: "Match attached photo color.",
    adminNotes: "Quoted $340",
    status: "quoted",
    createdAt: "2026-08-01T16:00:00.000Z",
  },
];

export const adminBlogSeed: AdminBlogPost[] = BLOG_POSTS.map((post) => ({
  _id: `blog_${post.id}`,
  category: post.category,
  title: post.title,
  excerpt: post.excerpt,
  image: post.image,
  slug: post.href.replace("/blog/", ""),
  body: post.body,
  published: true,
  createdAt: now,
}));

export const adminAffiliateProgramsSeed: AdminAffiliateProgram[] = [
  {
    _id: "ap_1",
    label: "For Everybody",
    title: "Referral Program",
    description: "Earn rewards when friends shop Iconive.",
    image: "/Image/ImagesPage/ladies.webp",
    isActive: true,
  },
  {
    _id: "ap_2",
    label: "Creators",
    title: "Content Creators",
    description: "Partner with us for content collaborations.",
    image: "/Image/ImagesPage/why-choose-us.webp",
    isActive: true,
  },
  {
    _id: "ap_3",
    label: "Stylists",
    title: "Stylist Program",
    description: "Exclusive benefits for professional stylists.",
    image: "/Image/ImagesPage/gents.webp",
    isActive: true,
  },
];

export const adminAffiliateApplicationsSeed: AdminAffiliateApplication[] = [
  {
    _id: "aa_1",
    name: "Maya Brooks",
    email: "maya@creator.com",
    phone: "+12025550999",
    message: "I create wig transform content on Instagram.",
    program: "Content Creators",
    status: "pending",
    createdAt: "2026-08-02T10:00:00.000Z",
  },
  {
    _id: "aa_2",
    name: "Rina Patel",
    email: "rina@salon.com",
    message: "Salon stylist interested in partner pricing.",
    program: "Stylist Program",
    status: "approved",
    createdAt: "2026-07-20T10:00:00.000Z",
  },
];

export const adminCustomersSeed: AdminCustomer[] = [
  {
    _id: DUMMY_IDS.user,
    name: "Demo User",
    email: "demo@iconive.com",
    phone: "+8801700000000",
    role: "user",
    isWholeSaler: false,
    gender: "female",
    dateOfBirth: "1995-04-12",
    addressCount: 2,
    createdAt: now,
  },
  {
    _id: "cust_2",
    name: "Sarah Ahmed",
    email: "sarah@example.com",
    phone: "+8801711222333",
    role: "user",
    isWholeSaler: false,
    addressCount: 1,
    createdAt: "2026-07-15T10:00:00.000Z",
  },
  {
    _id: "cust_3",
    name: "Beauty Hub BD",
    email: "orders@beautyhub.com",
    phone: "+8801711000001",
    role: "user",
    isWholeSaler: true,
    addressCount: 1,
    createdAt: "2026-06-01T10:00:00.000Z",
  },
];

export const adminFaqsSeed: AdminFaq[] = FAQS.map((faq, index) => ({
  _id: `faq_${index + 1}`,
  question: faq.question,
  answer: faq.answer,
  sortOrder: index + 1,
  isActive: true,
}));

export const adminReviewsSeed: AdminReview[] = PRODUCT_REVIEWS.map((review) => ({
  _id: `review_${review.id}`,
  name: review.name,
  rating: review.rating,
  title: review.title,
  comment: review.comment,
  images: review.images,
  verified: Boolean(review.verified),
  productId: DUMMY_IDS.product1,
  isPublished: true,
  createdAt: now,
}));

export const adminSettingsSeed: AdminSettings = {
  deliveryCharge: 20,
  fxRate: 106,
  freeShippingThreshold: 250,
  contactEmail: "info@iconivewigs.com",
  whatsappNumber: "+8801700000000",
  socialLinks: [
    { label: "Facebook", href: "https://facebook.com" },
    { label: "Instagram", href: "https://instagram.com" },
    { label: "YouTube", href: "https://youtube.com" },
  ],
};
